### ISSUE TITLE
Add photospline 2.0

### ISSUE THREAD

**Issue by jvansanten** [WIPACrepo/cvmfs#40]
Photospline 2.0 can peacefully coëxist with photospline the I3 project, and having it in py2-v3 would significantly ease the transition.

https://github.com/cnweaver/photospline/releases/tag/v2.0.0

**Comment by dsschult** [comment]
Is that the final location of the repository, or will it be moved under IceCube or WIPAC?

**Comment by jvansanten** [comment]
I'm open to moving it, though I don't see a pressing reason to do so. Maybe @cnweaver has an opinion?
