### ISSUE TITLE
add condor pybindings

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/cvmfs#48]
We should encourage usage of the HTCondor python bindings.  In order to do that, install them for the python in cvmfs.

Can do this for py2-v3 and future.

**Comment by jvansanten** [comment]
How portable are the pybindings across HTCondor releases? This sounds like something that might be fragile for sites that are not Madison.

**Comment by dsschult** [comment]
This is now `pip install`able, thanks to the condor team.  I guess this version doesn't have every feature of the src-built one, but has most of them.  I'll call it good enough.
