### ISSUE TITLE
boost::python::numpy

### ISSUE THREAD

**Issue by dsschult** [WIPACrepo/cvmfs#49]
boost::python::numpy is officially supported as of 1.63.  We should stop installing our own version.

Note that affects py2-v3, which should be cleaned up.

**Comment by jvansanten** [comment]
It looks like mainline boost::numpy is fairly bare-bones. In particular, it does not include any machinery for generating broadcasting wrappers for member functions (e.g. `boost::numpy::dstream::method`). Much of the complexity of Martin's implementation is necessary to work without variadic templates, though, so perhaps it's easier to get that in now?

**Comment by dsschult** [comment]
py2-v3.0.1 drops Martin's implementation.  This at least allows MuonGun to import.  Whether it's exactly what we want is left to @jvansanten .
