### ISSUE TITLE
python -> python3 missing

### ISSUE THREAD

**Issue by briedel** [WIPACrepo/cvmfs#56]
If `python` is missing setup.sh gets angry:

```
[riedel1@dt-login01 build]$ eval `/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/setup.sh`
/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/setup.sh: line 118: python: command not found
/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/setup.sh: line 118: python: command not found
/cvmfs/icecube.opensciencegrid.org/py3-v4.1.1/setup.sh: line 125: python: command not found
```

check needs to look for `python2` and `python3` as well rather than just `python`

**Comment by cnweaver** [comment]
It would be nice to just remove the dependency on python for running the set-up; none of the scripts in the `setup` directory does anything complex and can they be written, perhaps more simply, as shell scripts.

**Comment by dsschult** [comment]
They used to be shell scripts, and they were somewhat a mess.  I dislike writing complex things in uniform shell syntax (that must work in every shell version).
